insert into account (ACCT_NUMBER, ACCT_NAME, ACCT_TYPE, BALANCE_DATE ,CURRENCY ,OPENING_BALANCE) values (886975889, 'SGSavings121','SAVINGS',SYSDATE, 'SGD', 89135.01);
insert into account (ACCT_NUMBER, ACCT_NAME, ACCT_TYPE, BALANCE_DATE ,CURRENCY ,OPENING_BALANCE) values (345675880, 'ABSavings121','SAVINGS',SYSDATE, 'SGD', 199130.01);
insert into account (ACCT_NUMBER, ACCT_NAME, ACCT_TYPE, BALANCE_DATE ,CURRENCY ,OPENING_BALANCE) values (345675881, 'ABSavings122','SAVINGS',SYSDATE, 'AUD', 29913.01);
insert into account (ACCT_NUMBER, ACCT_NAME, ACCT_TYPE, BALANCE_DATE ,CURRENCY ,OPENING_BALANCE) values (345675882, 'ABSavings123','SAVINGS',SYSDATE, 'SGD', 399135.01);
insert into account (ACCT_NUMBER, ACCT_NAME, ACCT_TYPE, BALANCE_DATE ,CURRENCY ,OPENING_BALANCE) values (345675883, 'ABSavings124','SAVINGS',SYSDATE, 'SGD', 499135.01);
insert into account (ACCT_NUMBER, ACCT_NAME, ACCT_TYPE, BALANCE_DATE ,CURRENCY ,OPENING_BALANCE) values (345675884, 'ABSavings125','SAVINGS',SYSDATE, 'SGD', 599135.01);
insert into account (ACCT_NUMBER, ACCT_NAME, ACCT_TYPE, BALANCE_DATE ,CURRENCY ,OPENING_BALANCE) values (345675885, 'ABSavings126','Current',SYSDATE, 'AUD', 699135.01);
insert into account (ACCT_NUMBER, ACCT_NAME, ACCT_TYPE, BALANCE_DATE ,CURRENCY ,OPENING_BALANCE) values (345675886, 'ABSavings127','SAVINGS',SYSDATE, 'SGD', 799135.01);
insert into account (ACCT_NUMBER, ACCT_NAME, ACCT_TYPE, BALANCE_DATE ,CURRENCY ,OPENING_BALANCE) values (345675887, 'ABSavings128','SAVINGS',SYSDATE, 'SGD', 899135.01);
insert into account (ACCT_NUMBER, ACCT_NAME, ACCT_TYPE, BALANCE_DATE ,CURRENCY ,OPENING_BALANCE) values (345675888, 'ABSavings129','SAVINGS',SYSDATE, 'SGD', 2991.01);
insert into account (ACCT_NUMBER, ACCT_NAME, ACCT_TYPE, BALANCE_DATE ,CURRENCY ,OPENING_BALANCE) values (345675889, 'ABSavings110','Current',SYSDATE, 'SGD', 7935.01);
insert into account (ACCT_NUMBER, ACCT_NAME, ACCT_TYPE, BALANCE_DATE ,CURRENCY ,OPENING_BALANCE) values (345675810, 'ABSavings111','Current',SYSDATE, 'USD', 13135.01);

insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (1,886975889,SYSDATE,'SGD',null,'113.0','CR','TRN1 NO FEE');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (2,345675881,SYSDATE,'AUD',null,'234.0','CR','TRN2 SAL PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (3,345675881,SYSDATE,'AUD',null,'235.0','CR','TRN3 BKT PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (4,886975889,SYSDATE,'SGD',null,'236.0','CR','TRN4 BKT PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (5,886975889,SYSDATE,'USD',null,'237.0','CR','TRN5 SWFT PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (6,886975889,SYSDATE,'SGD',null,'238.0','CR','TRN7 FX PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (7,345675881,SYSDATE,'USD',null,'239.0','CR','TRN8 SAL PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (8,345675810,SYSDATE,'SGD',null,'100.0','CR','TRN9 SAL PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (9,345675881,SYSDATE,'FJD',null,'200.0','CR','TRN10 SAL PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (10,345675888,SYSDATE,'FJD',null,'145.0','CR','TRN11 SAL PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (11,345675888,SYSDATE,'SGD',null,'132.0','CR','TRN12 SAL PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (12,345675882,SYSDATE,'AUD',null,'678.0','CR','TRN13 SAL PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (13,345675882,SYSDATE,'AUD',null,'567.0','CR','TRN14 SAL PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (14,345675883,SYSDATE,'AUD',null,'123.0','CR','TRN15 SAL PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (15,345675883,SYSDATE,'FJD',null,'144.0','CR','TRN16 SAL PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (16,345675884,SYSDATE,'USD',null,'345.0','CR','TRN17 SAL PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (17,345675884,SYSDATE,'USD',22.56,null,'DR','TRN18 SAL PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (18,345675885,SYSDATE,'AUD',99.11,null,'DR','TRN19 SAL PAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (19,345675885,SYSDATE,'AUD',122.11,null,'DR','TRN19 BKT');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (20,345675887,SYSDATE,'SUD',522.11,null,'DR','TRN34 SWFT BPAY');
insert into transactions(ID,ACCT_NUMBER,BALANCE_DATE,CURRENCY,DEBIT_AMT,CREDIT_AMT,DRCR_TYPE,TXN_NARRATIVE) values (21,345675889,SYSDATE,'FJD',522.11,null,'DR','TRN34 SWFT BPAY');



	
  